server:
  port: 9090

spring:
  profiles: dev
  mvc:
    throw-exception-if-no-handler-found: true
  application:
    name: docker-template
  datasource:
    url: jdbc:mysql://localhost:3306/docker-template?autoReconnect=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  output:
    ansi:
      enabled: always
