spring:
  application:
    name: docker-template
  profiles:
    active: dev
#  datasource:
#    url: jdbc:mysql://localhost:3306/docker-template-dev?autoReconnect=true&useSSL=false
#    username: user
#    password: password
#    driver-class-name: com.mysql.jdbc.Driver
#    platform: mysql
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQLDialect

  output:
    ansi:
      enabled: always
